kind: Deployment
apiVersion: apps/v1
metadata:
  name: version-deploy-green
  labels:
    app: version-deploy
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version-deploy
      version: green
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: version-deploy
        version: green
    spec:
      containers:
        - name: versioner
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
             cpu: 50m
          env:
            - name: VERSION
              value: "GREEN"
          image: carnsds/version-demo:latest
